### ISSUE TITLE
端口改为8070以后，weexpack run web 访问不到呢

### ISSUE THREAD

**Issue by ggchxx** [ElemeFE/weex-vue-starter-kit#1]
端口改为8070以后，weexpack run web 访问不到呢，直接执行npm run dev 没有问题。，weexpack目录中的web.js的端口号已经改了

**Comment by ggchxx** [comment]
8080端口的 weexpack run web  也没法访问 是不是现在还不支持？

**Comment by csvwolf** [comment]
请问你修改的是：`build/dev.js` 目录吗 因为我们队 weexpack 的生成文件进行了一些修改 可能和他的命令目标文件不同。
