### ISSUE TITLE
Android build后 render error

### ISSUE THREAD

**Issue by jiangtao** [ElemeFE/weex-vue-starter-kit#10]

**Comment by feng-fu** [comment]
+1

**Comment by zhaokuohaha** [comment]
我的这边是 run android 或者 build Android的时候都出现 
```
Android project not found !

  You should run weexpack init first

 => Will start Android app

```
的问题, 可是我安卓模拟器已经打开了, 手机也连接调试模式了.  不知道怎么办.

**Comment by csvwolf** [comment]
#4 有解答

@zhaokuohaha weexpack add android 了么

**Comment by zhaokuohaha** [comment]
`weex platform add android` 有的

**Comment by zhaokuohaha** [comment]
错误的地方截图是这样子的: 
![错误截图](http://otheruse-1252035598.costj.myqcloud.com/weex_run_android_err.png)

我是按照知乎专栏上面的教程来做的
这是电脑正在运行的`新建安卓项目`以及设备列表(手机和模拟器):
![运行设备](http://otheruse-1252035598.costj.myqcloud.com/runing_diveces.png)

**Comment by zhaokuohaha** [comment]
搞定了, 原先不知道为什么 platforms > android > app 下只有src 文件夹, 只有编译后的代码.   这样再执行add android 的时候也会显示 已存在,  吧platforms下的android文件夹删掉, 在重新添加就好了
