### ISSUE TITLE
yarn 提示： koa-serve-static@0.0.1: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by daviscai** [ElemeFE/weex-vue-starter-kit#16]
yarn 安装时提示错误：
koa-serve-static@0.0.1: The engine "node" is incompatible with this module. Expected version "1.x.x".

应该是包版本太低了，但找不到是哪个包依赖它

**Comment by daviscai** [comment]
weex-devtool 这个包依赖了 koa-serve-static@0.0.1，用cnpm install 可以安装

**Comment by csvwolf** [comment]
依赖的新锅=。=可以去 weex-devtool 提 issue
