### ISSUE TITLE
关于编译生成js的疑问

### ISSUE THREAD

**Issue by hayvane** [ElemeFE/weex-vue-starter-kit#6]
1.通过npm run dev 生成的 js 文件在哪里？（native 端）
2.如果我有多个vue， 想生成多个js 如何配置？

**Comment by csvwolf** [comment]
@QingWei-Li

**Comment by dukelyuu** [comment]
@hayvane  run dev 是在内存跑的吧，只有build才是生成的打包文件。

**Comment by hayvane** [comment]
是的，我的意思是生成多个.js 文件，一个vue文件对应生成一个js文件。
这个我自己改好了，关了吧。

**Comment by py389172739** [comment]
@hayvane  请问你生成多个js怎么弄的？webpack怎么配置的，我弄了半天都没弄好，我也是做native开发的

**Comment by snowons** [comment]
@py389172739 改写你的webpack.config.js 中的entry，指定多个就可以了
eg:
```
function getBaseConfig () {
  return {
    entry: {
      'XXXA': path.join(__dirname, 'src', 'your-a.vue?entry=true'),
      'XXXBl': path.join(__dirname, 'src', 'your-b.vue?entry=true')
    },
    output: {
      path: 'dist/bundlejs/',
      filename: '[name].js'
    },
......
.....
}
```

**Comment by nothing-important** [comment]
@hayvane 请问你是怎么生成.vue对应的.js的文件呢？

**Comment by hayvane** [comment]
> @hayvane 请问你是怎么生成.vue对应的.js的文件呢？

见上文snowons给出的配置
