### ISSUE TITLE
关于npm run build打包后的部署

### ISSUE THREAD

**Issue by yinlsea** [ElemeFE/weex-vue-starter-kit#7]
npm run build打包生成dist目录后，部署到web服务后无显示

**Comment by csvwolf** [comment]
具体怎么说 有报错信息之类的么？

**Comment by yinlsea** [comment]
没看到有什么报错信息
![image](https://cloud.githubusercontent.com/assets/21033870/23777950/bf35efe2-0572-11e7-8671-da4b1e266f10.png)
编译后把这个直接部署到web服务器，访问index.html没有任何效果，npm run dev开发时正常

**Comment by yinlsea** [comment]
测试试用，基本没改什么内容

**Comment by csvwolf** [comment]
=0= 这个 index.html 里面啥东西。。。

**Comment by acgpiano** [comment]
@yinlsea @csvwolf
那是因为web打包时没有打weex-vue-render
修改/build/prod.js
`webConfig.entry = {
  app: ['./src/render.js', './src/app.js']
}`
我提了个pull request

**Comment by yinlsea** [comment]
确实是这个问题

**Comment by yinlsea** [comment]
这样确实能解决，但是打包出来的index.web.js就大了，有900K，不似用weex-tookit创建的web项目打包的小，直接在index.html加入
![image](https://cloud.githubusercontent.com/assets/21033870/23824031/1494d7ae-06aa-11e7-8a80-1ecc0de96dc2.png)不起效果

**Comment by acgpiano** [comment]
@yinlsea 
1.weex-vue-render默认打包是未压缩的，你可以用压缩后的只有90几k，修改src/render.js
`import weexVueRenderer from 'weex-vue-render/index.min.js'`
2.直接引用不清楚了，你要看看那个源码是怎么加载的了

**Comment by yinlsea** [comment]
好的，谢谢了！
