### ISSUE TITLE
引入mint-ui后出现render error:2013

### ISSUE THREAD

**Issue by wsrhp** [ElemeFE/weex-vue-starter-kit#8]
按照readme初始化了HelloWorld，一切正常。playground中正常，安卓模拟机上正常。

然后在src/app.js中加入
import MintUI from 'mint-ui'
import 'mint-ui/lib/style.css'
Vue.use(MintUI);
用来引入mint-ui，浏览器中localhost:8080页面正常显示mint-ui组件样式，而且F12打开调试板无任何报错。

但手机上playground扫码后就显示空白，运行weexpack run android之后安卓模拟机页面显示“render error：2013”

请问该怎么调整？多谢

**Comment by wsrhp** [comment]
看了下weex的官方文档，大概明白了……目前weex只支持一部分web平台的标准和组件……
https://weex-project.io/cn/references/web-standards.html

**Comment by csvwolf** [comment]
标签是按照 Native 标准来得 所以不能使用
